format = """
[î‚¶](#7A348E)\
$os\
$username\
[î‚°](bg:#FA027D fg:#7A348E)\
$directory\
[î‚°](fg:#FA027D bg:#FC8160)\
$git_branch\
$git_status\
[î‚°](fg:#FC8160 bg:#06669A)\
$docker_context\
$kubernetes\
[î‚°](fg:#06669A bg:#A696E6)\
$time\
[î‚° ](fg:#A696E6)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like ï„   or disable this
# and use the os module below
[username]
show_always = false
style_user = "bg:#7A348E"
style_root = "bg:#7A348E"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#7A348E"
disabled = true      # Disabled by default

[directory]
style = "bg:#FA027D"
format = "[ $path ]($style)"
truncation_length = 0
truncation_symbol = "â€¦/"
truncate_to_repo = false

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
#"Documents" = "ó°ˆ™ "
#"Downloads" = "ï€™ "
#"Music" = "ï€ "
#"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ó°ˆ™ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ó°ˆ™ " = " ó°ˆ™ï„ª "

[docker_context]
symbol = "ğŸ³ "
style = "bg:#06669A"
format = '[ $symbol $context ]($style)'

[kubernetes]
disabled = false
symbol = "âš“ "
style = "bg:#06669A"
format = '[ $symbol $context \($namespace\) ]($style)'

[git_branch]
symbol = "ï˜"
style = "bg:#FC8160"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FC8160"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%H:%M"         # Hour:Minute:Seconds Format
style = "bg:#A696E6"
format = '[ $time ]($style)'
